#!/bin/sh

# Shortcut to start up SemWiktionary
# Author: Matti Schneider-Ghibaudo

USE_GROWL=0 # [Growl](http://growl.info/) is a notification system for OS X

if [[ $1 = "--growl" ]]
then
	USE_GROWL=1
	shift
fi

if java -cp $(dirname $0)/bin:$(dirname $0)/lib/*:$(dirname $0)/lib/neo4j/* edu.unice.polytech.kis.semwiktionary.SemWiktionary "$@"
then 
	if [[ $USE_GROWL = 1 ]]
	then growlnotify -t "Parsing succeeded" -m "SemWiktionary parsing succeeded!"
	fi
else
	if [[ $USE_GROWL = 1 ]]
	then growlnotify -t "Parsing failed" -m "SemWiktionary parsing failed  :(" -p High
	fi
fi